name: Release Please

on:
    push:
        branches: [main]
        paths-ignore:
        - '.github/**'

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') == false
        steps:
            - uses: googleapis/release-please-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
